#!/bin/bash


#  __        ___    _     _          ____
#  \ \      / / \  | |   | |        |  _ \
#   \ \ /\ / / _ \ | |   | |   _____| | | |
#    \ V  V / ___ \| |___| |__|_____| |_| |
#     \_/\_/_/   \_\_____|_____|    |____/


DIR="" # Path to wallpapers
Monitor1=$(xrandr --listactivemonitors | grep "+" | awk '{print $4}' | awk NR==1) # Select the first monitor for dual mode
Monitor2=$(xrandr --listactivemonitors | grep "+" | awk '{print $4}' | awk NR==2) # Select the second monitor for dual mode

usage() {
    echo "Wall-d: A simple and fast wallpaper manager for x"
    echo ""
    echo "Usage:"
    echo "-h print this help message and exit"
    echo "-d path/to/your/wallpapers"
    echo "-r restore last set Wallpaper(s)"
    echo ""
}


restore() {

    defaultwallpaper.sh
}


while getopts :d:rh option; do
    case "${option}" in
        d) DIR=${OPTARG};;
        r) restore && exit;;
        h) usage && exit 0 ;;
        *) usage && exit 0
    esac
done

if [ -z "$DIR" ]; then
    usage && exit 0
fi

Single(){
    walls=$(sxiv -t -o -r -b -g 500x500+500+200 $DIR | xargs)  # running sxiv in thumbnail mode.
    wall1=$(printf "%s" "$walls" | awk '{w = 1; for (--w; w >=0; w--){printf "%s\t",$(NF-w)}print ""}') # Only print the last marked Wallpaper

    # if no picture is marked in sxiv, exit.
    if [ -z "$walls" ]
    then
      exit 0
    else
      $SingleWallMenu
    fi

    SingleWallMenu="dmenu -i -l 5 -p "Options""
    SingleWallOptions=$(echo -e "zoom\ncenter\ntile\nstretch\nno-randr" | $SingleWallMenu)

    xwallpaper --$SingleWallOptions $wall1  && sed -i "s|xwallpaper.*|xwallpaper  --$SingleWallOptions $wall1|" $HOME/.local/bin/defaultwallpaper.sh
}

# to set to diffrent wallpapers on each desktop
Dual() {
    dwalls=$(sxiv -t -o -r -b -g 500x500+500+200 $DIR | xargs)  # running sxiv in thimbnail mode.
    dwallslast2=$(printf "%s" "$dwalls" | awk '{w = 2; for (--w; w >=0; w--){printf "%s\t",$(NF-w)}print ""}') # Only print the two last marked Wallpapers
    dwall1=$(printf "%s" "$dwallslast2" | awk '{print $1}')  # Print the path to the before-last marked wallpaper
    dwall2=$(printf "%s" "$dwallslast2" | awk '{print $2}')  # Print the path to the last marked wallpaper

    # if no picture is marked in sxiv, exit.
    if [ -z "$dwalls" ]
    then
      exit 0
    else
      $FirstMonitorMenu
    fi

    FirstMonitorMenu="dmenu -i -l 4 -p "First_screen_options""
    FirstMonitorOptions=$(echo -e "zoom\ncenter\ntile\nstretch" | $FirstMonitorMenu)
    SecondMonitorMenu="dmenu -i -l 4 -p "Second_screen_options""
    SecondMonitorOptions=$(echo -e "zoom\ncenter\ntile\nstretch" | $SecondMonitorMenu)

    xwallpaper --output $Monitor1 --$FirstMonitorOptions $dwall1 --output $Monitor2 --$SecondMonitorOptions $dwall2 && sed -i "s|xwallpaper.*|xwallpaper --output $Monitor1 --$FirstMonitorOptions $dwall1 --output $Monitor2 --$SecondMonitorOptions $dwall2|" $HOME/.local/bin/defaultwallpaper.sh
}

MENU="dmenu -l 2 -p "Mode?""
MODE=$(echo -e "Single: Choose one Wallpaper\nDual: Choose two Wallpapers" | $MENU)
  case "$MODE" in
    Single*) Single ;;
    Dual*) Dual
  esac
